### PR TITLE
Fixed some stuff.

### PR DESCRIPTION
**Pull request by Rain288**
- Tuned the theme of the "Resources" page to fit the rest of the site
- Fixed inconsistencies in the "About" section of the site
- Cleaned up the "Docs" section to not look broken
- Added a margin-bottom to posters_name div's so the text below them isn't too close to it
- Removed Dark.css since it hasn't been used in months

### CODE REVIEW

**Comment by g4s-slack** [comment]
Hey!
The !membersheet command does not exist anymore, so this PR could be a good opportunity to remove that from `/docs`. I actually don't know the purpose of the page honestly so will just tag @therightmandev for some more info :)

**Comment by therightmandev** [comment]
@god4saken good call, this page has no purpose anymore.

**Comment by therightmandev** [comment]
@g4s-slack ^

**Comment by therightmandev** [comment]
On the navbar it could be replaced by the member app, which I plan on finishing today (even though I don't know if I can)

**Pull request merged**
